image: '947875592751.dkr.ecr.us-east-1.amazonaws.com/tools/node-build:release'

before_script:
  - node --version
  - echo ${DIST_TAG}
  - echo $(git describe --tags | sed -e 's/^v//')

stages:
  - Build
  - Publish

.publish:
  stage: Publish
  script:
    - npm config set _auth $(echo -n $NEXUS_PUBLISHER_USERNAME:$NEXUS_PUBLISHER_PASSWORD | base64)
    - npm config set @sudoplatform:registry https://repo.tools.anonyome.com/repository/npm-hosted
    - yarn publish --verbose --tag ${DIST_TAG} --new-version $(git describe --tags | sed -e 's/^v//') --no-git-tag-version --non-interactive
  tags:
    - docker
  dependencies:
    - Build

.push:
  extends: .publish
  script:
    - npm config set @sudoplatform:registry https://repo.tools.anonyome.com/repository/npm-hosted
    - yarn global add @sudoplatform/sdk-publisher
    - npm config delete @sudoplatform:registry
    - sdk-publisher -t $(git describe --tags | sed -e 's/^v//') --githubAccessToken ${GITHUB_ACCESS_TOKEN} --gitlabAccessToken ${API_ACCESS_TOKEN}
    - npm config set @sudoplatform:registry https://registry.npmjs.org/
    - npm config set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
    - yarn publish --verbose --tag ${DIST_TAG} --new-version $(git describe --tags | sed -e 's/^v//') --no-git-tag-version --non-interactive --access public

Build:
  stage: Build
  before_script:
    - npm config set @anonyome:registry https://repo.tools.anonyome.com/repository/npm-hosted
    - yarn global add @anonyome/dependency-report
  script:
    - yarn --frozen-lockfile
    - yarn build
    - report-dependencies --outFile ./dependencies-report.json
  artifacts:
    paths:
      - lib/
      - docs/
      - dependencies-report.json
  tags:
    - docker
  only:
    - master
    - merge_requests
    - /alpha$/
    - /beta$/
    - /^v?\d+\.\d+\.\d+$/

Branch:
  extends: .publish
  variables:
    DIST_TAG: ${CI_COMMIT_REF_SLUG}
  only:
    - merge_requests

Master:
  extends: .publish
  variables:
    DIST_TAG: master
  only:
    - master

Alpha:
  extends: .publish
  variables:
    DIST_TAG: alpha
  only:
    - /alpha$/

Beta:
  extends: .push
  variables:
    DIST_TAG: beta
  only:
    - /beta$/

Release:
  extends: .push
  variables:
    DIST_TAG: latest
  only:
    - /^v?\d+\.\d+\.\d+$/
